
spring:
    application:
        name: gerproc
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:testdb
        username : sa
        password : 
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate.ddl-auto: create
        generate-ddl: true
        show-sql: true
    h2:
        console:
            enabled: true
            path: /h2-console    

server:
    port: 8080
    
jwt:
    secret: 28%$.*YioTFFfgssjfh99e8dkhhs#$%&HGHNY%0jhgvgfyytTTRRR